---
plugins:
  - react
env:
  browser: true
  node: true
  es6: true
parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
globals:
  chrome: false
rules:
  semi: [warn, never]
  comma-dangle: [warn, always-multiline]
  no-dupe-args: error
  no-dupe-keys: error
  no-duplicate-case: error
  no-empty: warn
  no-empty-character-class: warn
  no-ex-assign: warn
  no-extra-parens: off
  no-extra-semi: warn
  no-func-assign: warn
  no-invalid-regexp: warn
  no-irregular-whitespace: warn
  no-undef: error
  no-unreachable: warn
  no-unused-vars: warn
  valid-typeof: warn
  # plugin:react
  react/boolean-prop-naming: warn
  react/jsx-boolean-value: warn
  react/jsx-child-element-spacing: warn
  react/jsx-closing-bracket-location: [warn, after-props]
  react/jsx-closing-tag-location: warn
  react/jsx-curly-spacing: warn
  react/jsx-equals-spacing: warn
  react/jsx-indent: [warn, 2]
  react/jsx-key: error
  react/jsx-no-comment-textnodes: error
  react/jsx-no-duplicate-props: error
  react/jsx-no-target-blank: error
  react/jsx-no-undef: error
  react/jsx-pascal-case: warn
  react/jsx-tag-spacing: warn
  react/jsx-uses-react: error
  react/jsx-uses-vars: warn
  react/no-children-prop: error
  react/no-danger-with-children: error
  react/no-deprecated: warn
  react/no-did-mount-set-state: warn
  react/no-did-update-set-state: error
  react/no-direct-mutation-state: error
  react/no-find-dom-node: warn
  react/no-is-mounted: warn
  react/no-render-return-value: error
  react/no-string-refs: warn
  react/no-this-in-sfc: error
  react/no-typos: error
  react/no-unescaped-entities: warn
  react/no-unknown-property: error
  react/no-unused-state: warn
  react/no-will-update-set-state: warn
  react/prefer-es6-class: warn
  react/react-in-jsx-scope: error
  react/require-render-return: error
  react/self-closing-comp: warn
  react/sort-comp: warn # nitpicky but potentially useful
  react/style-prop-object: error
  react/void-dom-elements-no-children: warn
