#!/usr/bin/env python
import os
import stat
import shutil

# Run this in its original directory!

config_file_pairs = [
  'ackrc',
  'bash_logout',
  'bash_profile',
  'bashrc',
  'gemrc',
  'gitconfig',
  'gitignore_global',
  'hgrc',
  'vim',
  'vimrc'
]

trash = '/tmp/tilde-originals'
if not os.path.exists(trash):
  os.makedirs(trash)

cwd = os.getcwd()
for src in config_file_pairs:
  dest = '../.%s' % src
  if os.path.exists(dest):
    if os.path.islink(dest):
      print "- %s already links to -> %s" % (dest, os.path.realpath(dest))
      print "- rm %s" % (dest)
      os.remove(dest)
    else:
      trash_dest = os.path.join(trash, dest.replace('../.', ''))
      print "- %s already exists." % (dest)
      print "- mv %s %s" % (dest, trash_dest)
      os.rename(dest, trash_dest)
  print 'ln -s %s %s' % (src, dest)
  os.symlink(src, dest)

bashrc_local = '../.bashrc.local'
if not os.path.exists(bashrc_local):
  print 'cp %s %s' % ('bashrc.local', bashrc_local)
  shutil.copyfile('bashrc.local', bashrc_local)